const DESKTOP_AMOUNT_CARDS = 12;
const DESKTOP_SCREEN_WIDTH = 1279;
const DESKTOP_SHOWCARD_STEP = 6;
const MOBILE_AMOUNT_CARDS = 5;
const TABLET_AMOUNT_CARDS = 8;
const TABLET_SCREEN_WIDTH = 600;
const TABLET_SHOWCARD_STEP = 4;

module.exports = {
  DESKTOP_SCREEN_WIDTH,
  TABLET_SCREEN_WIDTH,
  DESKTOP_AMOUNT_CARDS,
  TABLET_AMOUNT_CARDS,
  MOBILE_AMOUNT_CARDS,
  DESKTOP_SHOWCARD_STEP,
  TABLET_SHOWCARD_STEP,
}